name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend - Integration & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installation des dépendances Backend
        run: npm install

      - name: Exécution des tests Backend (si présents)
        run: npm test --if-present

  frontend-tests:
    name: Frontend - Tests & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installation des dépendances Frontend
        run: npm install

      - name: Exécution des tests Frontend (Vitest)
        run: npm test -- --watch=false --passWithNoTests --if-present